import Link from "next/link";
import { notFound, redirect } from "next/navigation";
import { createClient } from "@/lib/supabase/server";
import { latestByKey } from "@/lib/latestByKey";
import PrintButton from "@/components/PrintButton";
import concernConfig from "@/lib/concern-treatment-config.json";

const clinicName = process.env.NEXT_PUBLIC_CLINIC_NAME || "Your Clinic";

const CONCERN_LABELS = Object.fromEntries(
  concernConfig.concerns.map((c) => [c.id, c.label])
);
const TREATMENT_LABELS = Object.fromEntries(
  concernConfig.concerns.map((c) => [
    c.id,
    Object.fromEntries(c.treatments.map((t) => [t.id, t.label])),
  ])
);

function formatDate(iso) {
  return new Date(iso).toLocaleString(undefined, {
    month: "long",
    day: "numeric",
    year: "numeric",
    hour: "numeric",
    minute: "2-digit",
  });
}

export default async function VisitSharePage({ params }) {
  const { id } = await params;
  const supabase = await createClient();
  const {
    data: { user },
  } = await supabase.auth.getUser();

  if (!user) {
    redirect("/login");
  }

  const { data: visit } = await supabase
    .from("visits")
    .select(
      `id, created_at, notes,
       concern_scores(concern_key, ui_score),
       treatment_selections(concern_key, treatment_id, created_at)`
    )
    .eq("id", id)
    .single();

  if (!visit) {
    notFound();
  }

  const scores = [...(visit.concern_scores || [])].sort((a, b) => a.ui_score - b.ui_score);

  const latestTreatmentByConcern = latestByKey(
    visit.treatment_selections || [],
    (t) => t.concern_key
  );
  const treatments = [...latestTreatmentByConcern.values()];

  return (
    <main style={main}>
      <div className="print-hide" style={topLinks}>
        <Link href={`/visits/${id}`} style={backLink}>
          ← Back to visit
        </Link>
        <PrintButton />
      </div>

      <p style={eyebrow}>{clinicName}</p>
      <h1 style={{ marginTop: 4, marginBottom: 4 }}>Visit Summary</h1>
      <p style={{ color: "var(--color-text-muted)", marginTop: 0 }}>
        {formatDate(visit.created_at)}
      </p>

      <h2 style={sectionTitle}>Concern Scores</h2>
      {scores.length === 0 ? (
        <p style={{ color: "var(--color-text-muted)" }}>No scores recorded for this visit.</p>
      ) : (
        <table className="share-table">
          <thead>
            <tr>
              <th>Concern</th>
              <th>Score</th>
            </tr>
          </thead>
          <tbody>
            {scores.map((s) => (
              <tr key={s.concern_key}>
                <td>{CONCERN_LABELS[s.concern_key] || s.concern_key}</td>
                <td>{s.ui_score}/100</td>
              </tr>
            ))}
          </tbody>
        </table>
      )}

      <h2 style={sectionTitle}>Treatments Tried</h2>
      {treatments.length === 0 ? (
        <p style={{ color: "var(--color-text-muted)" }}>No treatments selected for this visit.</p>
      ) : (
        <table className="share-table">
          <thead>
            <tr>
              <th>Concern</th>
              <th>Treatment</th>
            </tr>
          </thead>
          <tbody>
            {treatments.map((t) => (
              <tr key={t.concern_key}>
                <td>{CONCERN_LABELS[t.concern_key] || t.concern_key}</td>
                <td>{TREATMENT_LABELS[t.concern_key]?.[t.treatment_id] || t.treatment_id}</td>
              </tr>
            ))}
          </tbody>
        </table>
      )}

      <p style={footnote}>
        Generated by the {clinicName} Skin Journey app for your provider&rsquo;s reference. Not a
        diagnosis — treatments shown are options your provider may recommend.
      </p>
    </main>
  );
}

const main = {
  maxWidth: 720,
  margin: "40px auto",
  padding: "0 24px",
};

const topLinks = {
  display: "flex",
  justifyContent: "space-between",
  alignItems: "center",
  marginBottom: 24,
  flexWrap: "wrap",
  gap: 8,
};

const backLink = {
  fontSize: 13,
  color: "var(--color-primary-dark)",
  textDecoration: "none",
};

const eyebrow = {
  color: "var(--color-text-muted)",
  fontSize: 13,
  margin: 0,
};

const sectionTitle = {
  fontSize: 16,
  marginTop: 32,
  marginBottom: 12,
};

const footnote = {
  marginTop: 32,
  fontSize: 12,
  color: "var(--color-text-muted)",
};
